'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CircleHelp, Cloud, Code2, Copy, Database, FileCheck2, Globe2, KeyRound, Layers, LoaderCircle, Map, Network, Orbit, RefreshCw, Satellite, Server, Shield, Users, Waypoints } from 'lucide-react';
import { api, setAdministratorKey, useApi } from '@/lib/api';
import { formatDate, formatTime } from '@/lib/constants';
import type { Page, SourceStatus } from '@/lib/types';
import { ErrorState, ExternalLink, Loading, Modal, StatusBadge } from './ui';

const descriptors: Record<string,{icon:React.ReactNode;subtitle:string;technology:string}> = {
  firms:{icon:<Satellite size={22} strokeWidth={1.4}/>,subtitle:'Real thermal observations',technology:'VIIRS · NOAA-20 / NOAA-21 / S-NPP'},
  sentinel:{icon:<Orbit size={22} strokeWidth={1.4}/>,subtitle:'Measured optical context',technology:'STAC + COG · cloud-masked NDVI / NDBI'},
  osm:{icon:<Map size={22} strokeWidth={1.4}/>,subtitle:'Infrastructure & land-use context',technology:'Overpass API · 1.5 km spatial query'},
  worldpop:{icon:<Users size={22} strokeWidth={1.4}/>,subtitle:'Optional population exposure',technology:'Population-count raster · reference year'},
  archive:{icon:<FileCheck2 size={22} strokeWidth={1.4}/>,subtitle:'Historical training & map replay',technology:'NASA-format CSV · pinned mirror · SHA-256'},
  model:{icon:<Waypoints size={22} strokeWidth={1.4}/>,subtitle:'Actual machine-learning inference',technology:'Python · scikit-learn · XGBoost'},
  storage:{icon:<Database size={22} strokeWidth={1.4}/>,subtitle:'Observation & analyst persistence',technology:'MongoDB 2dsphere / explicit local journal'},
};
export default function SourcesView({ refresh, onChecked, onPage, notify }: {refresh: number; onChecked: () => void; onPage: (page:Page) => void; notify: (message:string,error?:boolean)=>void}) {
  const source = useApi<{sources:SourceStatus[]; checkedAt:string; mutationAuthRequired:boolean}>('/api/sources',refresh);
  const [checking,setChecking]=useState(false);
  const [checkError,setCheckError]=useState<string|null>(null);
  const [admin,setAdmin]=useState(false);
  const [key,setKey]=useState('');
  async function check(){setChecking(true);setCheckError(null);try{await api('/api/sources/check',{method:'POST',body:'{}'});source.reload();onChecked();notify('Source checks finished. Each card shows the actual connection result.');}catch(error){setCheckError((error as Error).message);}finally{setChecking(false);}}
  const ready=source.data?.sources.filter(item=>item.status==='connected').length||0;
  const command=`# Optional: improves NASA spatial/date query control\nFIRMS_MAP_KEY=\n\n# Real MongoDB service (Docker Compose hostname)\nMONGODB_URI=mongodb://mongo:27017/thermoscan\n\n# Protect mutations before public deployment\nADMIN_API_KEY=\n\n# Optional genuine population-count GeoTIFF\nWORLDPOP_RASTER_URL=\nWORLDPOP_YEAR=`;
  return <div className="space-y-5">
    <section className="panel flex flex-wrap items-center justify-between gap-4 p-6"><div className="flex items-center gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f1f5f7] text-[#92a8b6]"><Network size={22} strokeWidth={1.4}/></div><div><h2 className="font-display text-[19px] font-semibold tracking-tight">Every signal has a source.</h2><p className="mt-1.5 text-[11px] text-[#92a3af]">{source.data?`${ready} of ${source.data.sources.length} components connected`:'Checking source state'} · Failures stay visible. Missing data stays missing.</p></div></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>setAdmin(true)}><KeyRound size={13}/>Admin access</button><button onClick={check} disabled={checking} className="btn-primary"><RefreshCw className={checking?'animate-spin':''} size={13}/>{checking?'Checking endpoints…':'Check connections'}</button></div></section>
    {(source.error||checkError)&&<ErrorState message={source.error||checkError||''} retry={source.reload}/>}
    {!source.data&&source.loading?<div className="panel"><Loading text="Reading integration health…"/></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{source.data?.sources.map(item=>{const descriptor=descriptors[item.id];return <section className="panel flex flex-col p-5" key={item.id}><div className="flex items-start justify-between gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f3f6f8] text-[#96aab7]">{descriptor?.icon||<Server size={22}/>}</span><StatusBadge state={item.status}/></div><h3 className="mt-4 text-[13px] font-semibold">{item.name}</h3><p className="mt-1 text-[10px] text-[#a0adb6]">{descriptor?.subtitle}</p><p className="mt-4 flex-1 text-[10px] leading-6 text-[#98a7b1]">{item.detail}</p><div className="mt-4 border-t border-[#edf1f3] pt-3"><p className="text-[8px] text-[#a4b1ba]">{descriptor?.technology}</p>{item.lastAttempt&&<p className="mt-1.5 text-[8px] text-[#b1bac1]">Checked {formatDate(item.lastAttempt)} · {formatTime(item.lastAttempt)} UTC</p>}{item.observedThrough&&<p className="mt-1 text-[8px] text-[#a4b1ba]">Latest observation: {formatDate(item.observedThrough)} {formatTime(item.observedThrough)} UTC</p>}{item.url&&<ExternalLink href={item.url} className="mt-3 text-[10px]">Open source documentation</ExternalLink>}</div></section>;})}</div>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="panel p-6"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-xs font-semibold"><Code2 size={16} className="text-[#9badb9]"/>Configure the real services</h3><button aria-label="Copy environment configuration" className="icon-button" onClick={()=>navigator.clipboard.writeText(command).then(()=>notify('Environment template copied. Add real secrets only to your local .env.')).catch(()=>notify('Clipboard unavailable. Select the template to copy it.',true))}><Copy size={13}/></button></div><p className="mt-3 text-[10px] leading-6 text-[#9cabb5]">Use <code className="rounded bg-[#f0f4f6] px-1.5 py-0.5 text-[#8298a7]">.env.example</code> as your template. Credentials remain server-side and are never embedded in browser URLs or committed to Git.</p><pre className="mt-4 overflow-x-auto rounded-lg bg-[#24343f] p-4 font-mono text-[9px] leading-6 text-[#a8bdca]">{command}</pre><div className="mt-4 flex flex-wrap gap-4 text-[10px]"><ExternalLink href="https://firms.modaps.eosdis.nasa.gov/api/map_key/">Get a free NASA MAP_KEY</ExternalLink><ExternalLink href="https://www.mongodb.com/docs/atlas/">MongoDB setup</ExternalLink></div></section>
      <section className="panel p-6"><h3 className="text-xs font-semibold">What works without credentials?</h3><div className="mt-5 space-y-5">{[['NASA public regional feeds','The real 24-hour, 48-hour and 7-day VIIRS CSV downloads need no MAP_KEY. This app fetches 7 days to preserve recurrence context.'],['Sentinel-2 via Earth Search','A public STAC mirror of Copernicus imagery, with no account required. Raster reads must also reach the public Sentinel COG bucket.'],['OpenStreetMap Overpass','Public, bounded spatial queries. Requests are cached and failures are surfaced; missing map coverage is not treated as negative ground truth.'],['Local historical analysis','The bundled replay is a checksum-verified subset of genuine source rows. It is always labelled historical, regardless of today’s date.']].map(([title,body])=><div key={title} className="flex items-start gap-3"><Check className="mt-0.5 shrink-0 text-[#91aa99]" size={13}/><div><h4 className="text-[11px] font-medium text-[#8195a3]">{title}</h4><p className="mt-1 text-[10px] leading-5 text-[#a1aeb7]">{body}</p></div></div>)}</div><div className="mt-5 rounded-lg bg-[#f7f4ef] p-4 text-[10px] leading-6 text-[#ad967c]">Near-real-time does not mean continuous or instantaneous. Regional downloads are updated hourly; this app checks sources every 15 minutes by default. Original acquisition and retrieval times are preserved.</div></section>
    </div>
    <div className="flex items-start gap-3 rounded-xl border border-[#e2e9ed] bg-[#f0f5f8] p-5"><Shield size={17} className="mt-0.5 shrink-0 text-[#91a7b5]"/><div><h3 className="text-[11px] font-medium text-[#8298a7]">Prototype deployment boundary</h3><p className="mt-1.5 text-[10px] leading-6 text-[#9babb6]">MongoDB is used when a real instance is configured and reachable. Otherwise, the UI names the local file journal explicitly. Add authentication, source monitoring, an independently validated model, and an audited notification workflow before any public-safety deployment.</p></div></div>
    {admin&&<Modal title="Administrator access" onClose={()=>setAdmin(false)}><p className="text-xs leading-6 text-[#93a4af]">{source.data?.mutationAuthRequired?'This server protects training, imports and review actions with ADMIN_API_KEY. Enter your own configured key for this browser session.':'This development instance has no ADMIN_API_KEY configured. Mutations are rate-limited but not authenticated. Set an administrator key before public deployment.'}</p><label htmlFor="administrator-key" className="mt-5 block text-[10px] text-[#93a4af]">Session-only administrator key</label><input id="administrator-key" type="password" autoComplete="off" className="field mt-2" placeholder="Your configured ADMIN_API_KEY" value={key} onChange={event=>setKey(event.target.value)}/><p className="mt-2 text-[9px] leading-5 text-[#afbac2]">Kept in browser memory only. Not saved to local storage or sent to third-party data sources. Do not use your GitHub credentials here.</p><div className="mt-5 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>{setAdministratorKey('');setKey('');setAdmin(false);notify('Administrator key cleared from this browser session.');}}>Clear session</button><button className="btn-primary" onClick={()=>{setAdministratorKey(key);setKey('');setAdmin(false);notify('Session access configured. Authorization is checked by the server on each action.');}}>Use for this session</button></div></Modal>}
  </div>;
}
